name: CMake

on:
  [push, pull_request]

env: 
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install utils
      run: |
        sudo apt install valgrind
        echo "Valgrind installed"
        sudo apt install lcov
        echo "Lcov installed"
        pip install wheel
        echo "wheel installed"
        pip install cpplint
        echo "cpplint installed"
        
    - name: Linters report
      run: make check

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_FOR_TEST=1

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Generate report
      working-directory: ${{github.workspace}}/build
      run: |
        lcov -t "tests" -o coverage.info -c -d bitInversion/ -d bitCounter/
        genhtml -o report coverage.info

    - uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: build/report
      
    - name: Memtest
      run: make memtest